server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:stock_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
polygon:
  api:
    base-url: ${POLYGON_API_BASE_URL:https://api.polygon.io}
    api-key: ${POLYGON_API_KEY:put_your_api_key_here}

logging:
  level:
    root: DEBUG
    com.sstjerne.stockapi: DEBUG 

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
      group:
        custom:
          include: db,diskSpace
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true


  